Traceback (most recent call last):
  File "/Users/peterliang/Desktop/Neruobit_Python/Report/main.py", line 696, in <module>
    report(le_data, re_data, l_mdata)
  File "/Users/peterliang/Desktop/Neruobit_Python/Report/main.py", line 269, in report
    story = content(doc, data1, data2)
  File "/Users/peterliang/Desktop/Neruobit_Python/Report/main.py", line 137, in content
    paste([summary_figure_le, summary_figure_re], "summary.png")
  File "/Users/peterliang/Desktop/Neruobit_Python/Report/main.py", line 233, in paste
    im_list = [pImage.open(fn) for fn in img_list]
  File "/Users/peterliang/Desktop/Neruobit_Python/Report/main.py", line 233, in <listcomp>
    im_list = [pImage.open(fn) for fn in img_list]
  File "/Users/peterliang/anaconda3/envs/cv/lib/python3.7/site-packages/PIL/Image.py", line 2931, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/Users/peterliang/Desktop/Neruobit_Python/Report/summary.svg'
